services:
  blockchain_server1:
    image: gtanjsbusiness/simple_blockchain:latest
    environment:
      - HTTP_PORT=8080
    ports:
      - "8080:8080"

  blockchain_server2:
    image: gtanjsbusiness/simple_blockchain:latest
    environment:
      - HTTP_PORT=8080
      - PEERS=blockchain_server1:8080
    ports:
      - "8081:8080"
    depends_on:
      - blockchain_server1

  blockchain_server3:
    image: gtanjsbusiness/simple_blockchain:latest
    environment:
      - HTTP_PORT=8080
      - PEERS=blockchain_server1:8080,blockchain_server2:8080
    ports:
      - "8082:8080"
    depends_on:
      - blockchain_server1
      - blockchain_server2