name: Deploy to Production

on:
  push:
    branches:
      - main  # Workflow will trigger only when there's a push to the main branch

jobs:
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_CREDENTIALS }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'

      - name: Configure Docker
        run: |
          gcloud auth configure-docker
      
      - name: Build
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/myapp:latest .

      - name: Push
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/myapp:latest

      - name: Deploy
        run: |
          gcloud run deploy myapp \
          --region asia-east1 \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/myapp \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }}